version: '3'

services:
  db:
    image: postgres:14.2-alpine
    restart: "always"
    shm_size: "128mb"
    volumes:
        - ./postgres-data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD-Postgres123}
    healthcheck:
      test: "pg_isready -U postgres"
  redis:
    image: redis:6.0.6-alpine
    restart: "always"
    ports:
      - 6379:6379
    healthcheck:
      test: "redis-cli ping"
  api:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "2"
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - ENVIRONMENT=${ENVIRONMENT-production}
      - DEBUG=${DEBUG-FALSE}
      - SECRET_KEY=${SECRET_KEY}
      - SENTRY_DSN_KEY
      - API_SUPERUSER_PASSWORD=${API_SUPERUSER_PASSWORD-Root123}
      - API_SUPERUSER_TOKEN=${API_SUPERUSER_TOKEN-891b4b17feab99f3ff7e5b5d04ccc5da7aa96da6}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - API_INTERNAL_BASE_URL=${API_INTERNAL_BASE_URL-http://api:8000}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-AAAA}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-AAAA}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME-AAAA}
      - AWS_REGION_NAME=${AWS_REGION_NAME-AAAA}
      - ERRBIT_URL
      - ERRBIT_KEY
      - FLOWER_USER=${FLOWER_USER-root}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD-Root123}
      - FLOWER_HOST=${FLOWER_HOST-flower}
      - FLOWER_PORT=${FLOWER_PORT-5555}
    healthcheck:
      test: "curl --silent --fail http://localhost:8000/version/ || exit 1"
  celery:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=default ./start_celery_worker.sh -P prefork -Q default -c 2"]
    restart: "always"
    depends_on:
      - redis    
    healthcheck:
      test: ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=default ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-AAAA}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-AAAA}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME-AAAA}
      - AWS_REGION_NAME=${AWS_REGION_NAME-AAAA}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_indexing:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=indexing ./start_celery_worker.sh -P prefork -Q indexing -c 2"]
    restart: "always"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=indexing ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_concurrent:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=concurrent ./start_celery_worker.sh -P prefork -Q concurrent -c 2"]
    restart: "always"
    depends_on:
      - redis
    healthcheck:
      test:  ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=concurrent ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-AAAA}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-AAAA}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME-AAAA}
      - AWS_REGION_NAME=${AWS_REGION_NAME-AAAA}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_0_1:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=bulk_import_0_1 ./start_celery_worker.sh -Q bulk_import_0,bulk_import_1 -c 1"]
    restart: "always"
    depends_on:
      - redis
    healthcheck:
      test:  ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_0_1 ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_2_3:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=bulk_import_2_3 ./start_celery_worker.sh -Q bulk_import_2,bulk_import_3 -c 1"]
    restart: "always"
    depends_on:
      - redis
    healthcheck:
      test:  ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_2_3 ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_root:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "CELERY_WORKER_NAME=bulk_import_root ./start_celery_worker.sh -Q bulk_import_root -c 1"]
    restart: "always"
    depends_on:
      - redis
    healthcheck:
      test:  ["CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_root ./ping_celery_worker.sh"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
      - API_BASE_URL=${API_BASE_URL-http://localhost:8000}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  flower:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: ["bash", "-c", "./start_flower.sh"]
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_PASSWORD=${DB_PASSWORD-Postgres123}
      - ES_HOST=${ES_HOST-es}
      - ES_PORT=${ES_PORT-9200}
      - FLOWER_USER=${FLOWER_USER-root}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD-Root123}
      - REDIS_HOST=${REDIS_HOST-redis}
      - REDIS_PORT=${REDIS_PORT-6379}
    restart: "always"
    healthcheck:
      test: "curl --silent --fail -u $${FLOWER_USER:-root}:$${FLOWER_PASSWORD:-Root123} http://localhost:5555/metrics || exit 1"
  es:
    image: elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    user: "1000:1000"
    volumes:
      - ./es-data/data:/usr/share/elasticsearch/data
    restart: "always"
    healthcheck:
      test: "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
  kibana:
    image: kibana:7.8.1
    ports:
     - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200

volumes:
  postgres-data:
  master-db:
  es-data:
